# Generated by Django 4.2.19 on 2025-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulapp', '0002_fuelrate_delete_fuelpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
    ]
