# Generated by Django 4.2.19 on 2025-02-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulapp', '0003_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
