# Generated by Django 4.2.19 on 2025-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulapp', '0004_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
