# Generated by Django 4.2.19 on 2025-02-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulapp', '0005_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
